### ISSUE TITLE
[Feat] Create "activation time" 

### ISSUE THREAD

**Issue by hugomvlopes** [vostpt/bot#138]
When VOST it's on activation the bot says how many hours since the start of the activation.
Only the founders can !startactivation and !stopactivation.
When someone type !ativacao bot display how many time activation have started in hours.

- Only Founders can send to the bot a command, for example,

  -  `!vostia start activation <activation_name>`
  As soon as the command is sent, the bot should return a message to the public channel #vost-portugal-publico with the message:
  > @everyone entramos agora em ativação devido a `<activation_name>`

  - `!vostia end activation <activation_name>`
  As soon as the command is sent, the bot should return a message to the public channel #vost-portugal-publico with the message:
  > @everyone acabou a ativação devido a `<activation_name>`. Obrigado!

  The bot should then return the total of hours since the start of the activation to the same public channel
- All users should be able to check, and get the information via PM, of current activation hours with a command, for example:
  - `!vostia stats activation <activation name>`

**Comment by tiagojpdias** [comment]
Regarding this feature request:

- What's an activation?
- What should be displayed?
- Is there any specific channel to reply to? Or it sends a DM with the info?
- The subset of users able to communicate the activation should be the "founders" group or should we create a whitelist of userIds?

We need more acceptance criteria in order to implement the feature the best way possible.

**Comment by JorgeMiguelGomes** [comment]
@tiagoad this command should work in the following manner:
- Only Founders can send to the bot a command, for example,` !vostia start activation <activation_name>. As soon as the command is sent, the bot should return a message to the public channel #vost-portugal-publico with the message "@everyone entramos agora em ativação devido a `<activation_name>`"
- The same goes for ending the activation, for example, ` !vostia end activation <activation_name>`. As soon as the command is sent, the bot should return a message to the public channel #vost-portugal-publico with the message "@everyone acabou a ativação devido a `<activation_name>`. Obrigado!"
- The bot should then return the total of hours since the start of the activation to the same public channel
- All users should be able to check, and get the information via PM, of current activation hours with a command, for example, !vostia stats activation <activation name> 

Please let me know if this is clear enough. Thank you.

**Comment by tiagojpdias** [comment]
Updated the issue with content from the previous comment.

**Comment by miguelcarreiro** [comment]
Closed due to inactivity.
