### ISSUE TITLE
[Feat] Monitor Google Sheet to notify Discord and Tweet

### ISSUE THREAD

**Issue by JorgeMiguelGomes** [vostpt/bot#158]
## Context
With the COVID-19 pandemic, the amount of data that has to be consumed, validated, and tweeted is immense. 
FAQ are a great way to gather information in one place, but we still need to make manual tweets to announce new insertions.

## Solution
Develop a feature on VOSTia that monitors a Google Sheet's responses and **when a  new response is inserted**:
- Alerts a certain channel on Discord
- Tweets **the question** on twitter automatically with a general link (to be provided) and with an image attached (to be provided)

**Comment by miguelcarreiro** [comment]
Since Twitter limits each tweet to 280 characters, we need to decide how to tweet questions or answers with > 280 characters (or less, if tweet includes emojis, hashtags and introduction).
A possible solution is:
1st tweet:
[Emojis?] [Hashtag?]
[Question intro]
[Question - 1st part] (...)
[Emojis?] 
2nd tweet:
[Emojis?] [Hashtag?]
(...) [Question - 2nd part].
[Emojis?]
3rd tweet:
[Emojis?]  [Hashtag?]
[Answer intro]
[Answer - 1st part] (...)
[Link?]
[Emojis?]
4th tweet:
[Emojis?]  [Hashtag?]
(...) [Answer - 2nd part].
[Link?]
[Emojis?]

**Comment by JorgeMiguelGomes** [comment]
> Since Twitter limits each tweet to 280 characters, we need to decide how to tweet questions or answers with > 280 characters (or less, if tweet includes emojis, hashtags and introduction).
> A possible solution is:
> 1st tweet:
> [Emojis?] [Hashtag?]
> [Question intro]
> [Question - 1st part] (...)
> [Emojis?]
> 2nd tweet:
> [Emojis?] [Hashtag?]
> (...) [Question - 2nd part].
> [Emojis?]
> 3rd tweet:
> [Emojis?] [Hashtag?]
> [Answer intro]
> [Answer - 1st part] (...)
> [Link?]
> [Emojis?]
> 4th tweet:
> [Emojis?] [Hashtag?]
> (...) [Answer - 2nd part].
> [Link?]
> [Emojis?]

**Let's keep this simple (executive decision mode)**
If Question fits on a single tweet 

- including emojis info and microbe at the beginning 
- including hashtags #COVID19PT and #COVID19PTFAQ 
- including text: "Nova resposta à pergunta `question`"
- including emojis info and microbe at the end 
**then question is posted including direct link and image (to be developed)**

If Question doesn't fit on single tweet
**Send tweet with** 
- emojis info and microbe at the beginning 
- hashtags #COVID19PT and #COVID19PTFAQ 
- including text "Nova resposta no #COVID19EstamosON" 
- emojis info and microbe at the end 
- direct link to new answer 

@miguelcarreiro let's do this

**Comment by JorgeMiguelGomes** [comment]
Closing issue as it is no longer relevant.
